name: Build and test

on: [push]

jobs:
  build_app:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup
      run: cmake -Dtest=ON .

    - name: Build
      run: make

    - name: Test
      run: make test

    - name: 'Upload artifacts'
      uses: actions/upload-artifact@v2
      with:
        name: app
        path: app
        retention-days: 15