name: Build the binary

on: [push]

jobs:
  build_app:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup
      run: cmake .

    - name: Build
      run: make

    - name: 'Upload artifacts'
      uses: actions/upload-artifact@v2
      with:
        name: app
        path: vfs
        retention-days: 15